version: '3.8'

services:
  db-qa:
    image: postgres:15
    container_name: db-qa
    environment:
      POSTGRES_DB: ventas-app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./db/ventas-app.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  db-prod:
    image: postgres:15
    container_name: db-prod
    environment:
      POSTGRES_DB: ventas-prod
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./db/ventas-prod.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  ventas-app:
    build: ./ventas-app
    ports:
      - "8080:8080"

  ventas-frontend:
    build: ./ventas-frontend
    ports:
      - "3000:3000"
